"""Validation.

Two layers.  ``check_tree`` inspects what was generated on disk and needs no
running server; it is what CI runs.  ``check_live`` speaks HTTP to a running
Caddy and asserts the contract the Caddyfile is supposed to implement — status
codes, content types, method semantics and the absence of the backend's
identity.

The checks that matter most are the negative ones: no external resource, no
internal address, no secret-shaped string and no marker identifying the
generator.  A decoy that phones out to a font CDN has failed regardless of how
convincing it looks.
"""

from __future__ import annotations

import json
import re
import ssl
import urllib.error
import urllib.request
from dataclasses import dataclass, field
from pathlib import Path
from typing import List, Optional, Tuple

EXTERNAL_URL_RE = re.compile(
    r"""(?:src|href|action|content)\s*=\s*["'](?:https?:)?//([^/"']+)""",
    re.IGNORECASE,
)
IMPORT_RE = re.compile(r"@import\s+(?:url\()?['\"]?(?:https?:)?//", re.IGNORECASE)
PRIVATE_IP_RE = re.compile(
    r"\b(?:127\.\d+\.\d+\.\d+|10\.\d+\.\d+\.\d+|192\.168\.\d+\.\d+"
    r"|172\.(?:1[6-9]|2\d|3[01])\.\d+\.\d+|0\.0\.0\.0|::1)\b"
)
LOCALHOST_RE = re.compile(r"\blocalhost\b", re.IGNORECASE)
SECRET_RE = re.compile(
    r"(?i)\b(?:api[_-]?key|secret[_-]?key|password|passwd|private[_-]?key|"
    r"bearer\s+[a-z0-9._-]{16,}|BEGIN\s+(?:RSA|OPENSSH|PRIVATE)\s+KEY)\b"
)
MARKER_RE = re.compile(r"(?i)selfsteal|remnawave|xray|reality|generated by")

TEXT_SUFFIXES = {".html", ".css", ".json", ".xml", ".txt", ".svg"}


@dataclass
class Report:
    checks: int = 0
    failures: List[str] = field(default_factory=list)
    warnings: List[str] = field(default_factory=list)

    def ok(self) -> bool:
        return not self.failures

    def check(self, condition: bool, message: str) -> bool:
        self.checks += 1
        if not condition:
            self.failures.append(message)
        return condition

    def warn(self, condition: bool, message: str) -> None:
        self.checks += 1
        if not condition:
            self.warnings.append(message)

    def merge(self, other: "Report") -> "Report":
        self.checks += other.checks
        self.failures.extend(other.failures)
        self.warnings.extend(other.warnings)
        return self


def check_tree(webroot: Path, domain: str) -> Report:
    report = Report()
    webroot = Path(webroot)

    required = ["index.html", "404.html", "style.css", "favicon.svg",
                "favicon.ico", "robots.txt", "sitemap.xml",
                ".well-known/security.txt"]
    for name in required:
        report.check((webroot / name).exists(), f"missing required file: {name}")

    ico = webroot / "favicon.ico"
    if ico.exists():
        blob = ico.read_bytes()
        report.check(blob[:4] == b"\x00\x00\x01\x00",
                     "favicon.ico is not a valid ICO container")
        report.check(len(blob) > 64, "favicon.ico is implausibly small")

    for path in sorted(webroot.rglob("*")):
        if not path.is_file() or path.suffix not in TEXT_SUFFIXES:
            continue
        rel = path.relative_to(webroot).as_posix()
        if rel.startswith(".selfsteal"):
            continue
        try:
            text = path.read_text("utf-8")
        except (OSError, UnicodeDecodeError):
            report.failures.append(f"{rel}: not readable as UTF-8")
            continue

        for host in EXTERNAL_URL_RE.findall(text):
            host = host.split(":")[0].lower()
            if host and host != domain:
                report.failures.append(f"{rel}: references external host {host}")
        report.check(not IMPORT_RE.search(text), f"{rel}: remote CSS @import")
        report.check(not PRIVATE_IP_RE.search(text),
                     f"{rel}: contains a private or loopback IP address")
        report.check(not LOCALHOST_RE.search(text), f"{rel}: mentions localhost")
        report.check(not SECRET_RE.search(text),
                     f"{rel}: contains a credential-shaped string")
        report.check(not MARKER_RE.search(text),
                     f"{rel}: leaks a generator or infrastructure marker")

        if path.suffix == ".json":
            try:
                json.loads(text)
            except ValueError as exc:
                report.failures.append(f"{rel}: invalid JSON ({exc})")
        if path.suffix == ".html":
            report.check("<html" in text.lower(), f"{rel}: missing <html>")
            report.check("</html>" in text.lower(), f"{rel}: unterminated document")
            report.check(text.lower().count("<body") == 1,
                         f"{rel}: expected exactly one <body>")

    sitemap = webroot / "sitemap.xml"
    if sitemap.exists():
        urls = re.findall(r"<loc>https://([^/]+)(/[^<]*)</loc>",
                          sitemap.read_text("utf-8"))
        report.check(bool(urls), "sitemap.xml lists no URLs")
        for host, url in urls:
            report.check(host == domain,
                         f"sitemap.xml references foreign host {host}")
            report.check(_resolves(webroot, url),
                         f"sitemap.xml lists {url}, which has no backing file")
            report.check(not url.startswith("/api"),
                         f"sitemap.xml lists API route {url}")

    robots = webroot / "robots.txt"
    if robots.exists():
        report.check("Sitemap:" in robots.read_text("utf-8"),
                     "robots.txt does not reference the sitemap")

    sec = webroot / ".well-known/security.txt"
    if sec.exists():
        body = sec.read_text("utf-8")
        report.check("Contact:" in body, "security.txt has no Contact field")
        report.check("Expires:" in body, "security.txt has no Expires field")

    return report


def _resolves(webroot: Path, url: str) -> bool:
    """Mirror the Caddy try_files chain for HTML routes."""
    rel = url.lstrip("/")
    if rel == "":
        return (webroot / "index.html").exists()
    candidates = [webroot / rel,
                  webroot / rel / "index.html",
                  webroot / (rel + ".html")]
    return any(c.is_file() for c in candidates)


# --------------------------------------------------------------------------
# live checks
# --------------------------------------------------------------------------

@dataclass
class Probe:
    path: str
    status: int
    content_type: Optional[str] = None
    method: str = "GET"
    json_body: bool = False


def _request(base: str, probe: Probe, timeout: float = 6.0) -> Tuple[int, dict, bytes]:
    context = ssl.create_default_context()
    context.check_hostname = False
    context.verify_mode = ssl.CERT_NONE
    req = urllib.request.Request(base.rstrip("/") + probe.path, method=probe.method)
    req.add_header("User-Agent", "Mozilla/5.0 (compatible; site-check/1.0)")
    try:
        with urllib.request.urlopen(req, timeout=timeout, context=context) as resp:
            return resp.status, dict(resp.headers), resp.read()
    except urllib.error.HTTPError as exc:
        return exc.code, dict(exc.headers), exc.read()


def default_probes(endpoints: List[str], pages: List[str]) -> List[Probe]:
    probes = [Probe("/", 200, "text/html")]
    probes += [Probe(p, 200, "text/html") for p in pages if p != "/"]
    probes += [Probe(e, 200, "application/json", json_body=True) for e in endpoints]
    probes += [
        Probe("/robots.txt", 200, "text/plain"),
        Probe("/sitemap.xml", 200, "text/xml"),
        Probe("/.well-known/security.txt", 200, "text/plain"),
        Probe("/favicon.ico", 200),
        Probe("/favicon.svg", 200, "image/svg+xml"),
        Probe("/style.css", 200, "text/css"),
        Probe("/does-not-exist-8f2c", 404, "text/html"),
        Probe("/.env", 404),
        Probe("/.git/HEAD", 404),
        Probe("/_api/api", 404),
        Probe("/", 200, method="HEAD"),
    ]
    if endpoints:
        probes += [
            Probe("/status.json", 200, "application/json", json_body=True),
            Probe(endpoints[0], 405, method="POST", json_body=True),
            Probe(endpoints[0], 204, method="OPTIONS"),
        ]
        api_root = next((e for e in endpoints if e.startswith("/api/")), None)
        if api_root:
            probes.append(Probe(api_root + "/definitely-missing", 404,
                                "application/json", json_body=True))
    return probes


def check_live(base: str, probes: List[Probe]) -> Report:
    report = Report()
    for probe in probes:
        try:
            status, headers, body = _request(base, probe)
        except Exception as exc:                      # noqa: BLE001 - reported
            report.failures.append(f"{probe.method} {probe.path}: {exc}")
            report.checks += 1
            continue
        report.check(status == probe.status,
                     f"{probe.method} {probe.path}: expected {probe.status}, "
                     f"got {status}")
        if probe.content_type:
            actual = headers.get("Content-Type", "")
            report.check(probe.content_type in actual,
                         f"{probe.method} {probe.path}: expected Content-Type "
                         f"{probe.content_type}, got {actual!r}")
        report.check("Server" not in headers,
                     f"{probe.method} {probe.path}: Server header present "
                     f"({headers.get('Server')!r}) — backend is identifiable")
        report.check("Alt-Svc" not in headers,
                     f"{probe.method} {probe.path}: Alt-Svc advertised")
        if probe.json_body and probe.method != "HEAD" and body:
            try:
                json.loads(body.decode("utf-8"))
            except (ValueError, UnicodeDecodeError) as exc:
                report.failures.append(
                    f"{probe.method} {probe.path}: body is not valid JSON ({exc})")
                report.checks += 1
    return report
