"""Validation.

Two layers.  ``check_tree`` inspects what was generated on disk and needs no
running server; it is what CI runs.  ``check_live`` speaks HTTP to a running
Caddy and asserts the contract the Caddyfile is supposed to implement — status
codes, content types, method semantics and the absence of the backend's
identity.

The checks that matter most are the negative ones: no external resource, no
internal address, no secret-shaped string and no marker identifying the
generator.  A decoy that phones out to a font CDN has failed regardless of how
convincing it looks.
"""

from __future__ import annotations

import http.client
import json
import re
import socket
import ssl
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import List, Optional, Tuple
from urllib.parse import urlsplit

EXTERNAL_URL_RE = re.compile(
    r"""(?:src|href|action|content)\s*=\s*["'](?:https?:)?//([^/"']+)""",
    re.IGNORECASE,
)
IMPORT_RE = re.compile(r"@import\s+(?:url\()?['\"]?(?:https?:)?//", re.IGNORECASE)
PRIVATE_IP_RE = re.compile(
    r"\b(?:127\.\d+\.\d+\.\d+|10\.\d+\.\d+\.\d+|192\.168\.\d+\.\d+"
    r"|172\.(?:1[6-9]|2\d|3[01])\.\d+\.\d+|0\.0\.0\.0|::1)\b"
)
LOCALHOST_RE = re.compile(r"\blocalhost\b", re.IGNORECASE)
SECRET_RE = re.compile(
    r"(?i)\b(?:api[_-]?key|secret[_-]?key|password|passwd|private[_-]?key|"
    r"bearer\s+[a-z0-9._-]{16,}|BEGIN\s+(?:RSA|OPENSSH|PRIVATE)\s+KEY)\b"
)
MARKER_RE = re.compile(r"(?i)selfsteal|remnawave|xray|reality|generated by")

TEXT_SUFFIXES = {".html", ".css", ".json", ".xml", ".txt", ".svg"}


@dataclass
class Report:
    checks: int = 0
    failures: List[str] = field(default_factory=list)
    warnings: List[str] = field(default_factory=list)

    def ok(self) -> bool:
        return not self.failures

    def check(self, condition: bool, message: str) -> bool:
        self.checks += 1
        if not condition:
            self.failures.append(message)
        return condition

    def warn(self, condition: bool, message: str) -> None:
        self.checks += 1
        if not condition:
            self.warnings.append(message)

    def merge(self, other: "Report") -> "Report":
        self.checks += other.checks
        self.failures.extend(other.failures)
        self.warnings.extend(other.warnings)
        return self


def check_tree(webroot: Path, domain: str) -> Report:
    report = Report()
    webroot = Path(webroot)

    required = ["index.html", "404.html", "style.css", "favicon.svg",
                "favicon.ico", "robots.txt", "sitemap.xml",
                ".well-known/security.txt"]
    for name in required:
        report.check((webroot / name).exists(), f"missing required file: {name}")

    ico = webroot / "favicon.ico"
    if ico.exists():
        blob = ico.read_bytes()
        report.check(blob[:4] == b"\x00\x00\x01\x00",
                     "favicon.ico is not a valid ICO container")
        report.check(len(blob) > 64, "favicon.ico is implausibly small")

    for path in sorted(webroot.rglob("*")):
        if not path.is_file() or path.suffix not in TEXT_SUFFIXES:
            continue
        rel = path.relative_to(webroot).as_posix()
        if rel.startswith(".selfsteal"):
            continue
        try:
            text = path.read_text("utf-8")
        except (OSError, UnicodeDecodeError):
            report.failures.append(f"{rel}: not readable as UTF-8")
            continue

        for host in EXTERNAL_URL_RE.findall(text):
            host = host.split(":")[0].lower()
            if host and host != domain:
                report.failures.append(f"{rel}: references external host {host}")
        report.check(not IMPORT_RE.search(text), f"{rel}: remote CSS @import")
        report.check(not PRIVATE_IP_RE.search(text),
                     f"{rel}: contains a private or loopback IP address")
        report.check(not LOCALHOST_RE.search(text), f"{rel}: mentions localhost")
        report.check(not SECRET_RE.search(text),
                     f"{rel}: contains a credential-shaped string")
        report.check(not MARKER_RE.search(text),
                     f"{rel}: leaks a generator or infrastructure marker")

        if path.suffix == ".json":
            try:
                json.loads(text)
            except ValueError as exc:
                report.failures.append(f"{rel}: invalid JSON ({exc})")
        if path.suffix == ".html":
            report.check("<html" in text.lower(), f"{rel}: missing <html>")
            report.check("</html>" in text.lower(), f"{rel}: unterminated document")
            report.check(text.lower().count("<body") == 1,
                         f"{rel}: expected exactly one <body>")

    sitemap = webroot / "sitemap.xml"
    if sitemap.exists():
        urls = re.findall(r"<loc>https://([^/]+)(/[^<]*)</loc>",
                          sitemap.read_text("utf-8"))
        report.check(bool(urls), "sitemap.xml lists no URLs")
        for host, url in urls:
            report.check(host == domain,
                         f"sitemap.xml references foreign host {host}")
            report.check(_resolves(webroot, url),
                         f"sitemap.xml lists {url}, which has no backing file")
            report.check(not url.startswith("/api"),
                         f"sitemap.xml lists API route {url}")

    robots = webroot / "robots.txt"
    if robots.exists():
        report.check("Sitemap:" in robots.read_text("utf-8"),
                     "robots.txt does not reference the sitemap")

    sec = webroot / ".well-known/security.txt"
    if sec.exists():
        body = sec.read_text("utf-8")
        report.check("Contact:" in body, "security.txt has no Contact field")
        report.check("Expires:" in body, "security.txt has no Expires field")

    return report


def _resolves(webroot: Path, url: str) -> bool:
    """Mirror the Caddy try_files chain for HTML routes."""
    rel = url.lstrip("/")
    if rel == "":
        return (webroot / "index.html").exists()
    candidates = [webroot / rel,
                  webroot / rel / "index.html",
                  webroot / (rel + ".html")]
    return any(c.is_file() for c in candidates)


# --------------------------------------------------------------------------
# live checks
# --------------------------------------------------------------------------

@dataclass
class Probe:
    path: str
    status: int
    content_type: Optional[object] = None   # str, or a tuple of acceptable values
    method: str = "GET"
    json_body: bool = False
    location_prefix: Optional[str] = None
    location_excludes: Optional[str] = None


class _PinnedConnection(http.client.HTTPSConnection):
    """Connect to a fixed address while presenting the site's own hostname.

    The backend is a name-based virtual host bound to loopback, so a probe has
    to dial 127.0.0.1 but still send SNI and Host for the real domain.  The
    first version of this checker connected straight to the IP; Python omits
    SNI for an IP literal, Caddy then had no site to match, and every probe
    died with TLSV1_ALERT_INTERNAL_ERROR while the site itself was fine.
    """

    def __init__(self, host, port, connect_addr, context, timeout):
        super().__init__(host, port, context=context, timeout=timeout)
        self._connect_addr = connect_addr

    def connect(self):
        self.sock = socket.create_connection(
            (self._connect_addr, self.port), self.timeout)
        self.sock = self._context.wrap_socket(self.sock, server_hostname=self.host)


def _connection(base: str, connect_addr: Optional[str], timeout: float):
    parts = urlsplit(base)
    host = parts.hostname or "127.0.0.1"
    port = parts.port or (443 if parts.scheme == "https" else 80)
    if parts.scheme != "https":
        return http.client.HTTPConnection(connect_addr or host, port, timeout=timeout)
    context = ssl.create_default_context()
    # The backend certificate is for the public domain and is served over
    # loopback; verifying it here would test DNS, not the site.
    context.check_hostname = False
    context.verify_mode = ssl.CERT_NONE
    if connect_addr:
        return _PinnedConnection(host, port, connect_addr, context, timeout)
    return http.client.HTTPSConnection(host, port, context=context, timeout=timeout)


def _request(base: str, probe: "Probe", timeout: float = 8.0,
             connect_addr: Optional[str] = None) -> Tuple[int, dict, bytes]:
    conn = _connection(base, connect_addr, timeout)
    try:
        conn.request(probe.method, probe.path, headers={
            "Host": urlsplit(base).hostname or "localhost",
            "User-Agent": "Mozilla/5.0 (compatible; site-check/1.0)",
            "Accept": "*/*",
            "Connection": "close",
        })
        resp = conn.getresponse()
        # Lower-cased keys: HTTP header names are case-insensitive, and a check
        # for "Server" that a different capitalisation slips past is worse than
        # no check at all.
        headers = {k.lower(): v for k, v in resp.getheaders()}
        return resp.status, headers, resp.read()
    finally:
        conn.close()


def wait_until_ready(base: str, connect_addr: Optional[str] = None,
                     timeout: float = 45.0) -> Optional[str]:
    """Poll until the backend answers, or return why it never did.

    A certificate may still be issuing when the installer reaches this point,
    so a single early failure is not evidence of a broken site.
    """
    deadline = time.monotonic() + timeout
    last = "no attempt made"
    while time.monotonic() < deadline:
        try:
            _request(base, Probe("/", 200), timeout=5.0, connect_addr=connect_addr)
            return None
        except Exception as exc:                       # noqa: BLE001 - reported
            last = str(exc)
            time.sleep(2.0)
    return last


def default_probes(endpoints: List[str], pages: List[str]) -> List[Probe]:
    probes = [Probe("/", 200, "text/html")]
    probes += [Probe(p, 200, "text/html") for p in pages if p != "/"]
    probes += [Probe(e, 200, "application/json", json_body=True) for e in endpoints]
    probes += [
        Probe("/robots.txt", 200, "text/plain"),
        Probe("/sitemap.xml", 200, ("application/xml", "text/xml")),
        Probe("/.well-known/security.txt", 200, "text/plain"),
        Probe("/favicon.ico", 200),
        Probe("/favicon.svg", 200, "image/svg+xml"),
        Probe("/style.css", 200, "text/css"),
        Probe("/does-not-exist-8f2c", 404, "text/html"),
        Probe("/.env", 404),
        Probe("/.git/HEAD", 404),
        Probe("/_api/api", 404),
        Probe("/", 200, method="HEAD"),
    ]
    if endpoints:
        probes += [
            Probe("/status.json", 200, "application/json", json_body=True),
            Probe(endpoints[0], 405, method="POST", json_body=True),
            Probe(endpoints[0], 204, method="OPTIONS"),
        ]
        api_root = next((e for e in endpoints if e.startswith("/api/")), None)
        if api_root:
            probes.append(Probe(api_root + "/definitely-missing", 404,
                                "application/json", json_body=True))
    return probes


def public_http_probes(domain: str, https_port: int = 8443) -> List[Probe]:
    """Probes for the :80 listener — the only Caddy surface facing the internet.

    It used to be checked by nobody.  The backend strips ``Server`` and
    ``Alt-Svc``; the redirect in front of it did not, so a single unauthenticated
    ``curl http://domain/`` identified the stack that everything behind it goes
    to some trouble to hide.  The Location assertions cover the other half of
    the contract: the redirect must reach the public 443 and must never disclose
    the backend port.
    """
    redirect_to = f"https://{domain}"
    return [
        Probe("/", 301, location_prefix=redirect_to,
              location_excludes=f":{https_port}"),
        Probe("/does-not-exist-8f2c", 301, location_prefix=redirect_to,
              location_excludes=f":{https_port}"),
        Probe("/.env", 301, location_prefix=redirect_to),
    ]


def check_live(base: str, probes: List[Probe],
               connect_addr: Optional[str] = None) -> Report:
    report = Report()
    unreachable = wait_until_ready(base, connect_addr)
    if unreachable is not None:
        report.checks += 1
        report.failures.append(
            f"backend at {base} did not answer within the timeout: {unreachable}")
        return report
    for probe in probes:
        try:
            status, headers, body = _request(base, probe, connect_addr=connect_addr)
        except Exception as exc:                      # noqa: BLE001 - reported
            report.failures.append(f"{probe.method} {probe.path}: {exc}")
            report.checks += 1
            continue
        report.check(status == probe.status,
                     f"{probe.method} {probe.path}: expected {probe.status}, "
                     f"got {status}")
        if probe.content_type:
            actual = headers.get("content-type", "")
            # A tuple means "any of these is correct". Caddy serves sitemap.xml
            # as application/xml; older versions said text/xml. Both are right,
            # and a checker that insists on one of them fails every real install
            # the day the server changes its mind.
            wanted = (probe.content_type if isinstance(probe.content_type, tuple)
                      else (probe.content_type,))
            report.check(any(candidate in actual for candidate in wanted),
                         f"{probe.method} {probe.path}: expected Content-Type "
                         f"{' or '.join(wanted)}, got {actual!r}")
        report.check("server" not in headers,
                     f"{probe.method} {probe.path}: Server header present "
                     f"({headers.get('server')!r}) — backend is identifiable")
        report.check("alt-svc" not in headers,
                     f"{probe.method} {probe.path}: Alt-Svc advertised")
        location = headers.get("location", "")
        if probe.location_prefix:
            report.check(location.startswith(probe.location_prefix),
                         f"{probe.method} {probe.path}: expected Location under "
                         f"{probe.location_prefix}, got {location!r}")
        if probe.location_excludes:
            report.check(probe.location_excludes not in location,
                         f"{probe.method} {probe.path}: Location leaks "
                         f"{probe.location_excludes!r} ({location!r})")
        if probe.json_body and probe.method != "HEAD" and body:
            try:
                json.loads(body.decode("utf-8"))
            except (ValueError, UnicodeDecodeError) as exc:
                report.failures.append(
                    f"{probe.method} {probe.path}: body is not valid JSON ({exc})")
                report.checks += 1
    return report
